---
# tasks file for roles/system-monitor-agent

- name: get current checkmk version
  local_action: 
    module: shell
    cmd: | 
       dpkg --info /etc/ansible/files/checkmk.deb |grep Version |tr -d ' Version: ' |sed 's/-1//'
    args:
      warn: no
  register: agent_local_check
  changed_when: false
    
- name: Check if agent is up to date
  shell: 
    cmd: | 
      cat /usr/bin/check_mk_agent |grep "Version: 1.6.0p" |sed 's/echo //' |tr -d '"' |tr -d 'Version: '
  args:
    warn: no
  register: agent_check
  changed_when: false
    
- name: copy checkmk
  copy:
    dest: /tmp/checkmk.deb
    src: checkmk.deb
    owner: root
    group: root
    mode: 0644
  when: agent_check.stdout != agent_local_check.stdout

- name: Remove check-mk-agent
  apt:
    name: check-mk-agent
    state: absent
  when: agent_check.stdout != agent_local_check.stdout
  
- name: Install check-mk-agent
  apt: 
    deb: /tmp/checkmk.deb
    force: yes
  when: agent_check.stdout != agent_local_check.stdout
  
- name: remove xinetd
  package:
    state: absent
    name: xinetd
  when: agent_check.stdout != agent_local_check.stdout
  
- name: check systemd version
  shell: 
    cmd: | 
      systemd --version |head -n1 |tr -d 'systemd ' | awk '{split($0,a,"("); print a[1]}'
  args:
    warn: no
  register: systemd_check
  changed_when: false
  when: agent_check.stdout != agent_local_check.stdout
  
- name: debug
  debug: var=systemd_check.stdout
- name: debug2
  debug: var=systemd_check.stdout
  when: systemd_check.stdout | int > 235
  
- name: set IPAllow for agent
  shell: 
    cmd: | 
      systemctl set-property check_mk.socket IPAddressDeny=any IPAddressAllow=172.16.254.98 IPAddressAllow=10.10.0.100
  args:
    warn: no
  register: ipallow_check
  changed_when: false
  when: (agent_check.stdout != agent_local_check.stdout) and (systemd_check.stdout | int > 235)
  
- name: check check_mk service
  systemd:
    state: started
    daemon_reload: yes
    name: check_mk.socket
    enabled: yes
  when: agent_check.stdout != agent_local_check.stdout
  
