---
# tasks file for roles/system-monitor-agent


- name: Check if agent is up to date
  shell: 
    cmd: | 
      cat /usr/bin/check_mk_agent |grep "Version: 1.6.0p" |sed 's/echo //' |tr -d '"' |tr -d 'Version: '
  args:
    warn: no
  register: agent_check
  changed_when: false
    
- name: copy checkmk
  copy:
    dest: /tmp/checkmk.deb
    src: check-mk-agent_1.6.0p20-1_all.deb
    owner: root
    group: root
    mode: 0644
  when: agent_check.stdout != "1.6.0p20" 

- name: Remove check-mk-agent
  apt:
    name: check-mk-agent
    state: absent
  when: agent_check.stdout != "1.6.0p20"
  
- name: Install check-mk-agent
  apt: 
    deb: /tmp/checkmk.deb
    force: yes
  when: agent_check.stdout != "1.6.0p20"

- name: check check_mk service
  systemd:
    state: started
    daemon_reload: yes
    name: check_mk.socket
    enabled: yes
