---
# tasks file for roles/system-monitor-agent


- name: Check if agent is up to date
  shell: 
    cmd: | 
      cat /usr/bin/check_mk_agent |grep "Version: 1.6.0p" |sed 's/echo //' |tr -d '"' |tr -d 'Version: '
  register: agent_check
    
- name: copy checkmk
  copy:
    dest: /tmp/checkmk.deb
    src: check-mk-agent_1.6.0p20-1_all.deb
    owner: root
    group: root
    mode: 0644
  when: agent_check.stdout != '1.6.0p20' or agent_check.stdout.find('No such file or directory') != -1
    
- name: Install my_package
  apt: deb="/tmp/checkmk.deb"
  when: agent_check.stdout != '1.6.0p20' or agent_check.stdout.find('No such file or directory') != -1

- name: check check_mk service
  systemd:
    state: restarted
    daemon_reload: yes
    name: check_mk.socket
    enabled: yes
