---
# tasks file for roles/system-monitor-agent

- name: Download checkmk
  get_url:
    url: https://172.16.254.98/twt/check_mk/agents/check-mk-agent_1.6.0p20-1_all.deb
    dest: /tmp/checkmk.deb
    validate_certs: no
    
- name: Install my_package
  apt: deb="/tmp/checkmk.deb"
    
- name: system packages | check-mk agent
  become: yes
  package:
    name: xinetd
    state: present

- name: xinetd | start and enable
  become: yes
  service:
    enabled: yes
    name: xinetd.service
    state: started
